In [126]:
import pandas as pd
import numpy as np
import os
import ast
#from joblib import Parallel, delayed
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import ast

In [127]:
movie_df = pd.read_csv('data/combined_metadata.csv')
movie_df = movie_df.drop(['Unnamed: 0'], axis=1)
movie_df

,adult,budget,genres,id,original_language,production_countries,revenue,runtime,spoken_languages,movieId,imdbId,tmdbId,views,likes,dislikes,n_trailers
0,False,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",3.735540e+08,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",1,114709,862.0,8050136,6330,1965,3
1,False,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",2.627972e+08,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",2,113497,8844.0,83048,70,14,1
2,False,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",8.145216e+07,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",4,114885,31357.0,104948,0,0,1
3,False,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",949,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",1.874368e+08,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",6,113277,949.0,32419,119,1,1
4,False,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",9091,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",6.435017e+07,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",9,114576,9091.0,6162,12,3,2
5,False,58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",710,en,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",3.521940e+08,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",10,113189,710.0,60593,138,9,4
6,False,62000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",9087,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",1.078795e+08,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",11,112346,9087.0,2728,3,0,1
7,False,44000000,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",10858,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",1.368176e+07,192.0,"[{'iso_639_1': 'en', 'name': 'English'}]",14,113987,10858.0,199605,399,16,1
8,False,98000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",1408,en,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",1.001732e+07,119.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",15,112760,1408.0,340713,353,24,1
9,False,52000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",524,en,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",1.161124e+08,178.0,"[{'iso_639_1': 'en', 'name': 'English'}]",16,112641,524.0,964716,1788,61,1
10,False,16500000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",4584,en,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",1.350000e+08,136.0,"[{'iso_639_1': 'en', 'name': 'English'}]",17,114388,4584.0,34129,92,2,2
11,False,4000000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",5,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",4.300000e+06,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",18,113101,5.0,707157,503,29,2
12,False,30000000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",9273,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",2.123855e+08,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",19,112281,9273.0,200934,17,0,2
13,False,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",11517,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",3.543111e+07,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",20,113845,11517.0,8240,10,0,1
14,False,30250000,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",8012,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",1.151016e+08,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",21,113161,8012.0,280984,605,49,2
15,False,50000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",9691,en,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",3.030307e+07,132.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",23,112401,9691.0,105322,134,9,1
16,False,3600000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",451,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",4.980000e+07,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",25,113627,451.0,642157,603,45,1
17,False,12000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",9263,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",2.740000e+07,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",27,114011,9263.0,131544,1065,12,1
18,False,18000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...",902,fr,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",1.738611e+06,108.0,"[{'iso_639_1': 'cn', 'name': '广州话 / 廣州話'}, {'i...",29,112682,902.0,52846,79,1,1
19,False,29500000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",63,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",1.688400e+08,129.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",32,114746,63.0,1073845,1299,80,1
20,False,30000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",9598,en,"[{'iso_3166_1': 'AU', 'name': 'Australia'}, {'...",2.541349e+08,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",34,112431,9598.0,110893,64,3,1
21,False,11000000,"[{'id': 18, 'name': 'Drama'}]",687,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",3.936364e+07,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",36,112818,687.0,822094,848,47,1
22,False,18000000,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",9312,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",1.221959e+08,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",44,113855,9312.0,1573578,4998,207,1
23,False,20000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",577,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",2.128451e+07,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",45,114681,577.0,204214,268,22,1
24,False,10000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",11861,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",2.357413e+07,116.0,"[{'iso_639_1': 'en', 'name': 'English'}]",46,113347,11861.0,98958,214,6,1
25,False,33000000,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...",807,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",3.273119e+08,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",47,114369,807.0,33367,33,1,1
26,False,55000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",10530,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",3.460798e+08,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",48,114148,10530.0,1604487,2211,171,2
27,False,6000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",629,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",2.334157e+07,106.0,"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso...",50,114814,629.0,2153660,3085,124,1
28,False,15000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",11448,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",6.700000e+06,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",52,113819,11448.0,49414,29,2,1
29,False,3500000,"[{'id': 35, 'name': 'Comedy'}]",10634,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",2.821592e+07,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",69,113118,10634.0,1021466,1939,74,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4793,False,7400000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",14395,hi,"[{'iso_3166_1': 'IN', 'name': 'India'}]",1.700000e+07,193.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",171737,449999,14395.0,316517,487,35,1
4794,False,10500000,"[{'id': 18, 'name': 'Drama'}, {'id': 37, 'name...",399019,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",2.544294e+07,93.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",171759,5592248,399019.0,2366786,6667,806,2
4795,False,34000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",339403,en,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2.245113e+08,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",171763,3890160,339403.0,9728699,48805,2323,2
4796,False,20000000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",397422,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",4.505677e+07,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",171867,4799050,397422.0,6488944,26044,15852,3
4797,False,3300000,"[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...",338517,ru,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",5.249225e+06,120.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",172093,4629032,338517.0,673132,0,0,1
4798,False,3500000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",37851,ru,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",2.294357e+06,0.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",172515,1620549,37851.0,96259,34,3,1
4799,False,7000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 878, '...",36698,ru,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1.877122e+06,90.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",172525,1245736,36698.0,232514,43,15,1
4800,False,3500000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",37656,ru,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",3.704408e+06,97.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",172527,1532382,37656.0,16500,38,2,1
4801,False,5000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 28, 'nam...",41978,ru,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1.756604e+07,115.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",172535,1438463,41978.0,106691,151,27,1
4802,False,80000000,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",324852,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",1.020063e+09,96.0,"[{'iso_639_1': 'en', 'name': 'English'}]",172547,3469046,324852.0,60083098,198101,17665,2
4803,False,60000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",333667,en,"[{'iso_3166_1': 'CN', 'name': 'China'}, {'iso_...",9.420546e+06,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",172573,2822672,333667.0,437373,1365,98,1
4804,False,6000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",102197,ru,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",4.588176e+06,99.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",172727,2321517,102197.0,185359,201,163,1
4805,False,5000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",375867,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",6.700000e+06,92.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",172809,4429194,375867.0,1127220,3653,549,1
4806,False,3000000,"[{'id': 35, 'name': 'Comedy'}]",52891,ru,"[{'iso_3166_1': 'UA', 'name': 'Ukraine'}, {'is...",9.713500e+06,99.0,"[{'iso_639_1': 'pl', 'name': 'Polski'}, {'iso_...",172833,1124396,52891.0,133964,262,117,1
4807,False,4000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",100791,ru,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",9.938268e+06,80.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",172885,2288121,100791.0,240166,0,0,1
4808,False,152000000,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",281338,en,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",3.699080e+08,140.0,"[{'iso_639_1': 'en', 'name': 'English'}]",173145,3450958,281338.0,34260341,142706,5899,5
4809,False,21000000,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",293768,en,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2.452716e+07,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",173161,1458169,293768.0,7583934,24386,1361,1
4810,False,197471676,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",339964,en,"[{'iso_3166_1': 'FR', 'name': 'France'}]",9.002429e+07,137.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",173291,2239822,339964.0,481852,4381,153,2
4811,False,7000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",272610,en,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",8.554500e+05,83.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",173405,3266724,272610.0,33847,53,108,1
4812,False,10000000,"[{'id': 10752, 'name': 'War'}, {'id': 28, 'nam...",326011,ru,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",7.547762e+06,120.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",173781,4187590,326011.0,355177,402,69,1
4813,False,5300000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",8453,hi,"[{'iso_3166_1': 'IN', 'name': 'India'}]",2.217591e+07,168.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",173827,439662,8453.0,1103456,1506,101,1
4814,False,30000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",341013,en,"[{'iso_3166_1': 'SE', 'name': 'Sweden'}, {'iso...",9.000794e+07,115.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}, {'iso...",173941,2406566,341013.0,8408074,47090,5661,4
4815,False,100000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",374720,en,"[{'iso_3166_1': 'NL', 'name': 'Netherlands'}, ...",5.198769e+08,107.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",174055,5013056,374720.0,54422395,377256,13600,4
4816,False,8500000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",14570,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",5.730596e+06,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",174147,89243,14570.0,34654,75,4,2
4817,False,8520000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",434119,ko,"[{'iso_3166_1': 'KR', 'name': 'South Korea'}]",5.610000e+07,125.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",174471,5606538,434119.0,66661,184,1,2
4818,False,260000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",335988,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",6.049421e+08,149.0,"[{'iso_639_1': 'en', 'name': 'English'}]",174585,3371366,335988.0,22567284,68842,6066,4
4819,False,3000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",57701,ru,"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1.957000e+06,90.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",174613,1820555,57701.0,321668,183,30,1
4820,False,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...",353491,en,"[{'iso_3166_1': 'ZA', 'name': 'South Africa'},...",7.100000e+07,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",175197,1648190,353491.0,26323050,128872,16471,2
4821,False,50000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",378236,en,"[{'iso_3166_1': 'US', 'name': 'United States o...",6.691394e+07,86.0,"[{'iso_639_1': 'en', 'name': 'English'}]",175475,4877122,378236.0,16314933,37065,132704,2
4822,False,11000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",395834,en,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",1.847702e+08,111.0,"[{'iso_639_1': 'en', 'name': 'English'}]",175569,5362988,395834.0,5885100,14834,988,3

In [128]:
movie_df['genres'] = movie_df.apply(lambda row: ast.literal_eval(row.genres), axis=1)
movie_df['production_countries'] = movie_df.apply(lambda row: ast.literal_eval(row.production_countries), axis=1)
movie_df['spoken_languages'] = movie_df.apply(lambda row: ast.literal_eval(row.spoken_languages), axis=1)

In [129]:
#movie_df['genres'][1][1]['name']
movie_df['production_countries'][2][0]['name']

'United States of America'

In [131]:
#movie_df['english'] = movie_df.apply(lambda row: (row.spoken_languages[0]['name'] == 'english'), axis=1)

In [142]:
def english (row):
    if row.spoken_languages:
        for lang in row.spoken_languages:
            if lang['name'] == 'English':
                return True
    return False
            
def numlang (row):
    if row.spoken_languages:
        return len(row.spoken_languages)

In [143]:
movie_df['English'] = movie_df.apply(english, axis=1)
movie_df['numlang'] = movie_df.apply(numlang, axis=1)

In [145]:
movie_df

,adult,budget,genres,id,original_language,production_countries,revenue,runtime,spoken_languages,movieId,imdbId,tmdbId,views,likes,dislikes,n_trailers,English,numlang
0,False,30000000,"[{u'id': 16, u'name': u'Animation'}, {u'id': 3...",862,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",3.735540e+08,81.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",1,114709,862.0,8050136,6330,1965,3,True,1.0
1,False,65000000,"[{u'id': 12, u'name': u'Adventure'}, {u'id': 1...",8844,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",2.627972e+08,104.0,"[{u'iso_639_1': u'en', u'name': u'English'}, {...",2,113497,8844.0,83048,70,14,1,True,2.0
2,False,16000000,"[{u'id': 35, u'name': u'Comedy'}, {u'id': 18, ...",31357,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",8.145216e+07,127.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",4,114885,31357.0,104948,0,0,1,True,1.0
3,False,60000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 80, ...",949,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",1.874368e+08,170.0,"[{u'iso_639_1': u'en', u'name': u'English'}, {...",6,113277,949.0,32419,119,1,1,True,2.0
4,False,35000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 12, ...",9091,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",6.435017e+07,106.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",9,114576,9091.0,6162,12,3,2,True,1.0
5,False,58000000,"[{u'id': 12, u'name': u'Adventure'}, {u'id': 2...",710,en,"[{u'iso_3166_1': u'GB', u'name': u'United King...",3.521940e+08,130.0,"[{u'iso_639_1': u'en', u'name': u'English'}, {...",10,113189,710.0,60593,138,9,4,True,3.0
6,False,62000000,"[{u'id': 35, u'name': u'Comedy'}, {u'id': 18, ...",9087,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",1.078795e+08,106.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",11,112346,9087.0,2728,3,0,1,True,1.0
7,False,44000000,"[{u'id': 36, u'name': u'History'}, {u'id': 18,...",10858,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",1.368176e+07,192.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",14,113987,10858.0,199605,399,16,1,True,1.0
8,False,98000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 12, ...",1408,en,"[{u'iso_3166_1': u'FR', u'name': u'France'}, {...",1.001732e+07,119.0,"[{u'iso_639_1': u'en', u'name': u'English'}, {...",15,112760,1408.0,340713,353,24,1,True,2.0
9,False,52000000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 80, u...",524,en,"[{u'iso_3166_1': u'FR', u'name': u'France'}, {...",1.161124e+08,178.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",16,112641,524.0,964716,1788,61,1,True,1.0
10,False,16500000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 10749...",4584,en,"[{u'iso_3166_1': u'GB', u'name': u'United King...",1.350000e+08,136.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",17,114388,4584.0,34129,92,2,2,True,1.0
11,False,4000000,"[{u'id': 80, u'name': u'Crime'}, {u'id': 35, u...",5,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",4.300000e+06,98.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",18,113101,5.0,707157,503,29,2,True,1.0
12,False,30000000,"[{u'id': 80, u'name': u'Crime'}, {u'id': 35, u...",9273,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",2.123855e+08,90.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",19,112281,9273.0,200934,17,0,2,True,1.0
13,False,60000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 35, ...",11517,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",3.543111e+07,103.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",20,113845,11517.0,8240,10,0,1,True,1.0
14,False,30250000,"[{u'id': 35, u'name': u'Comedy'}, {u'id': 53, ...",8012,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",1.151016e+08,105.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",21,113161,8012.0,280984,605,49,2,True,1.0
15,False,50000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 12, ...",9691,en,"[{u'iso_3166_1': u'FR', u'name': u'France'}, {...",3.030307e+07,132.0,"[{u'iso_639_1': u'en', u'name': u'English'}, {...",23,112401,9691.0,105322,134,9,1,True,3.0
16,False,3600000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 10749...",451,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",4.980000e+07,112.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",25,113627,451.0,642157,603,45,1,True,1.0
17,False,12000000,"[{u'id': 35, u'name': u'Comedy'}, {u'id': 18, ...",9263,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",2.740000e+07,100.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",27,114011,9263.0,131544,1065,12,1,True,1.0
18,False,18000000,"[{u'id': 14, u'name': u'Fantasy'}, {u'id': 878...",902,fr,"[{u'iso_3166_1': u'FR', u'name': u'France'}, {...",1.738611e+06,108.0,"[{u'iso_639_1': u'cn', u'name': u'广州话 / 廣州話'},...",29,112682,902.0,52846,79,1,1,False,2.0
19,False,29500000,"[{u'id': 878, u'name': u'Science Fiction'}, {u...",63,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",1.688400e+08,129.0,"[{u'iso_639_1': u'en', u'name': u'English'}, {...",32,114746,63.0,1073845,1299,80,1,True,2.0
20,False,30000000,"[{u'id': 14, u'name': u'Fantasy'}, {u'id': 18,...",9598,en,"[{u'iso_3166_1': u'AU', u'name': u'Australia'}...",2.541349e+08,89.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",34,112431,9598.0,110893,64,3,1,True,1.0
21,False,11000000,"[{u'id': 18, u'name': u'Drama'}]",687,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",3.936364e+07,122.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",36,112818,687.0,822094,848,47,1,True,1.0
22,False,18000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 14, ...",9312,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",1.221959e+08,101.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",44,113855,9312.0,1573578,4998,207,1,True,1.0
23,False,20000000,"[{u'id': 14, u'name': u'Fantasy'}, {u'id': 18,...",577,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",2.128451e+07,106.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",45,114681,577.0,204214,268,22,1,True,1.0
24,False,10000000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 10749...",11861,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",2.357413e+07,116.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",46,113347,11861.0,98958,214,6,1,True,1.0
25,False,33000000,"[{u'id': 80, u'name': u'Crime'}, {u'id': 9648,...",807,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",3.273119e+08,127.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",47,114369,807.0,33367,33,1,1,True,1.0
26,False,55000000,"[{u'id': 12, u'name': u'Adventure'}, {u'id': 1...",10530,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",3.460798e+08,81.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",48,114148,10530.0,1604487,2211,171,2,True,1.0
27,False,6000000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 80, u...",629,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",2.334157e+07,106.0,"[{u'iso_639_1': u'es', u'name': u'Español'}, {...",50,114814,629.0,2153660,3085,124,1,True,4.0
28,False,15000000,"[{u'id': 35, u'name': u'Comedy'}, {u'id': 1074...",11448,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",6.700000e+06,95.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",52,113819,11448.0,49414,29,2,1,True,1.0
29,False,3500000,"[{u'id': 35, u'name': u'Comedy'}]",10634,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",2.821592e+07,91.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",69,113118,10634.0,1021466,1939,74,1,True,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4793,False,7400000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 10749...",14395,hi,"[{u'iso_3166_1': u'IN', u'name': u'India'}]",1.700000e+07,193.0,"[{u'iso_639_1': u'en', u'name': u'English'}, {...",171737,449999,14395.0,316517,487,35,1,True,2.0
4794,False,10500000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 37, u...",399019,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",2.544294e+07,93.0,"[{u'iso_639_1': u'en', u'name': u'English'}, {...",171759,5592248,399019.0,2366786,6667,806,2,True,2.0
4795,False,34000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 80, ...",339403,en,"[{u'iso_3166_1': u'GB', u'name': u'United King...",2.245113e+08,113.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",171763,3890160,339403.0,9728699,48805,2323,2,True,1.0
4796,False,20000000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 35, u...",397422,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",4.505677e+07,101.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",171867,4799050,397422.0,6488944,26044,15852,3,True,1.0
4797,False,3300000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 10752...",338517,ru,"[{u'iso_3166_1': u'RU', u'name': u'Russia'}]",5.249225e+06,120.0,"[{u'iso_639_1': u'ru', u'name': u'Pусский'}]",172093,4629032,338517.0,673132,0,0,1,False,1.0
4798,False,3500000,"[{u'id': 28, u'name': u'Action'}, {u'id': 878,...",37851,ru,"[{u'iso_3166_1': u'RU', u'name': u'Russia'}]",2.294357e+06,0.0,"[{u'iso_639_1': u'ru', u'name': u'Pусский'}]",172515,1620549,37851.0,96259,34,3,1,False,1.0
4799,False,7000000,"[{u'id': 53, u'name': u'Thriller'}, {u'id': 87...",36698,ru,"[{u'iso_3166_1': u'RU', u'name': u'Russia'}]",1.877122e+06,90.0,"[{u'iso_639_1': u'ru', u'name': u'Pусский'}]",172525,1245736,36698.0,232514,43,15,1,False,1.0
4800,False,3500000,"[{u'id': 28, u'name': u'Action'}, {u'id': 878,...",37656,ru,"[{u'iso_3166_1': u'RU', u'name': u'Russia'}]",3.704408e+06,97.0,"[{u'iso_639_1': u'ru', u'name': u'Pусский'}]",172527,1532382,37656.0,16500,38,2,1,False,1.0
4801,False,5000000,"[{u'id': 35, u'name': u'Comedy'}, {u'id': 28, ...",41978,ru,"[{u'iso_3166_1': u'RU', u'name': u'Russia'}]",1.756604e+07,115.0,"[{u'iso_639_1': u'ru', u'name': u'Pусский'}]",172535,1438463,41978.0,106691,151,27,1,False,1.0
4802,False,80000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 16, ...",324852,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",1.020063e+09,96.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",172547,3469046,324852.0,60083098,198101,17665,2,True,1.0
4803,False,60000000,"[{u'id': 12, u'name': u'Adventure'}, {u'id': 1...",333667,en,"[{u'iso_3166_1': u'CN', u'name': u'China'}, {u...",9.420546e+06,90.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",172573,2822672,333667.0,437373,1365,98,1,True,1.0
4804,False,6000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 53, ...",102197,ru,"[{u'iso_3166_1': u'RU', u'name': u'Russia'}]",4.588176e+06,99.0,"[{u'iso_639_1': u'ru', u'name': u'Pусский'}]",172727,2321517,102197.0,185359,201,163,1,False,1.0
4805,False,5000000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 10749...",375867,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",6.700000e+06,92.0,"[{u'iso_639_1': u'en', u'name': u'English'}, {...",172809,4429194,375867.0,1127220,3653,549,1,True,2.0
4806,False,3000000,"[{u'id': 35, u'name': u'Comedy'}]",52891,ru,"[{u'iso_3166_1': u'UA', u'name': u'Ukraine'}, ...",9.713500e+06,99.0,"[{u'iso_639_1': u'pl', u'name': u'Polski'}, {u...",172833,1124396,52891.0,133964,262,117,1,False,2.0
4807,False,4000000,"[{u'id': 35, u'name': u'Comedy'}, {u'id': 14, ...",100791,ru,"[{u'iso_3166_1': u'RU', u'name': u'Russia'}]",9.938268e+06,80.0,"[{u'iso_639_1': u'ru', u'name': u'Pусский'}]",172885,2288121,100791.0,240166,0,0,1,False,1.0
4808,False,152000000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 878, ...",281338,en,"[{u'iso_3166_1': u'CA', u'name': u'Canada'}, {...",3.699080e+08,140.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",173145,3450958,281338.0,34260341,142706,5899,5,True,1.0
4809,False,21000000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 53, u...",293768,en,"[{u'iso_3166_1': u'GB', u'name': u'United King...",2.452716e+07,95.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",173161,1458169,293768.0,7583934,24386,1361,1,True,1.0
4810,False,197471676,"[{u'id': 12, u'name': u'Adventure'}, {u'id': 8...",339964,en,"[{u'iso_3166_1': u'FR', u'name': u'France'}]",9.002429e+07,137.0,"[{u'iso_639_1': u'fr', u'name': u'Français'}, ...",173291,2239822,339964.0,481852,4381,153,2,True,2.0
4811,False,7000000,"[{u'id': 18, u'name': u'Drama'}, {u'id': 80, u...",272610,en,"[{u'iso_3166_1': u'RU', u'name': u'Russia'}]",8.554500e+05,83.0,"[{u'iso_639_1': u'en', u'name': u'English'}, {...",173405,3266724,272610.0,33847,53,108,1,True,2.0
4812,False,10000000,"[{u'id': 10752, u'name': u'War'}, {u'id': 28, ...",326011,ru,"[{u'iso_3166_1': u'RU', u'name': u'Russia'}]",7.547762e+06,120.0,"[{u'iso_639_1': u'ru', u'name': u'Pусский'}]",173781,4187590,326011.0,355177,402,69,1,False,1.0
4813,False,5300000,"[{u'id': 28, u'name': u'Action'}, {u'id': 18, ...",8453,hi,"[{u'iso_3166_1': u'IN', u'name': u'India'}]",2.217591e+07,168.0,"[{u'iso_639_1': u'hi', u'name': u'हिन्दी'}, {u...",173827,439662,8453.0,1103456,1506,101,1,False,3.0
4814,False,30000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 53, ...",341013,en,"[{u'iso_3166_1': u'SE', u'name': u'Sweden'}, {...",9.000794e+07,115.0,"[{u'iso_639_1': u'sv', u'name': u'svenska'}, {...",173941,2406566,341013.0,8408074,47090,5661,4,True,4.0
4815,False,100000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 18, ...",374720,en,"[{u'iso_3166_1': u'NL', u'name': u'Netherlands...",5.198769e+08,107.0,"[{u'iso_639_1': u'en', u'name': u'English'}, {...",174055,5013056,374720.0,54422395,377256,13600,4,True,3.0
4816,False,8500000,"[{u'id': 28, u'name': u'Action'}, {u'id': 18, ...",14570,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",5.730596e+06,90.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",174147,89243,14570.0,34654,75,4,2,True,1.0
4817,False,8520000,"[{u'id': 28, u'name': u'Action'}, {u'id': 18, ...",434119,ko,"[{u'iso_3166_1': u'KR', u'name': u'South Korea'}]",5.610000e+07,125.0,"[{u'iso_639_1': u'ko', u'name': u'한국어/조선말'}]",174471,5606538,434119.0,66661,184,1,2,False,1.0
4818,False,260000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 878,...",335988,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",6.049421e+08,149.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",174585,3371366,335988.0,22567284,68842,6066,4,True,1.0
4819,False,3000000,"[{u'id': 35, u'name': u'Comedy'}, {u'id': 1074...",57701,ru,"[{u'iso_3166_1': u'RU', u'name': u'Russia'}]",1.957000e+06,90.0,"[{u'iso_639_1': u'ru', u'name': u'Pусский'}]",174613,1820555,57701.0,321668,183,30,1,False,1.0
4820,False,60000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 37, ...",353491,en,"[{u'iso_3166_1': u'ZA', u'name': u'South Afric...",7.100000e+07,95.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",175197,1648190,353491.0,26323050,128872,16471,2,True,1.0
4821,False,50000000,"[{u'id': 35, u'name': u'Comedy'}, {u'id': 1075...",378236,en,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",6.691394e+07,86.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",175475,4877122,378236.0,16314933,37065,132704,2,True,1.0
4822,False,11000000,"[{u'id': 28, u'name': u'Action'}, {u'id': 80, ...",395834,en,"[{u'iso_3166_1': u'GB', u'name': u'United King...",1.847702e+08,111.0,"[{u'iso_639_1': u'en', u'name': u'English'}]",175569,5362988,395834.0,5885100,14834,988,3,True,1.0